
version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HTTP_PORT}:80
      # - ${NGINX_HTTPS_PORT}:443/tcp
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      # - BACKEND_HOST=${BACKEND_HOST}
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_conf/common:/etc/nginx/conf.d/common:ro
      - ./nginx_conf/templates:/etc/nginx/templates:ro
      - ./nginx_log:/var/log/nginx
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
      - ${ADMIN_DIST:-/root/alfa-automatic/build}:/var/www/admin
      - ./auto_reload.sh:/docker-entrypoint.d/auto_reload.sh
    ulimits:
      nproc: 65535
      nofile:
        soft: 110000
        hard: 150000
    restart: unless-stopped
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; sleep 12h & wait $${!}; done;'"










